
name: Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
 first_job:
  name: job1
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python fun.py
        
